### ISSUE TITLE
Navigation tags seem to be getting incorrect data

### ISSUE THREAD

**Issue by skrichten** [NodeSquarespace/node-squarespace-server#138]
This one is strange because I'm not sure how to consistently reproduce it.  Also, I think I've seen instances where the local server gets it right and squarespace gets it wrong!  

The issue that I see at the moment  is occurring when I have a main navigation with folders and I navigate to a page within a folder.  Looking at the main nav JSON data... On Squarespace, the parent folder of the page I navigated to has ```folderActive: true``` and the page has ``` folderActive: false```, but when loading the page on the local server this is reversed.  This is making it difficult for me to make drop down navigation.

My folder.conf file looks like this...

```
{
  "title" : "Folder",
  "folder": true,
  "addText": "Add Page",
  "acceptTypes" : [ "gallery", "page", "press", "events"],
  "icon" : "folder"
}
```
With the exception of "page" the types are all custom.  I have no "system collections" in template.conf.

**Comment by kitajchuk** [comment]
@skrichten I'm pretty sure I know what's going on here. I need to make sure the node server accurately sets the `folderActive` and `active` properties in the navigation JSON. I believe currently it is trying to set them with the same condition which is likely why its the reverse of what you see on Squarespace.

**Comment by kitajchuk** [comment]
@skrichten I got in there and fussed around under the hood. The server definitely wasn't correctly setting the `folderActive` flag for navigation context items. Recreating that format is slightly more complicated than I had originally anticipated. Anyway, it seems to be working now and I published a new version of the server `+ node-squarespace-server@0.4.9`. Let me know if you notice anything else amiss. I tested my local against my remote and got the context objects matching up for both navigation and folder-navigation implementations.

**Comment by skrichten** [comment]
Still having problems here.  If I am on a page within a folder, the folder still has folderActive = false on my local server, fodlerActive = true on squarespace.  See JSON from my console below.  Local on the left, Squarespace on the right.  And yes, I updated and busted cache :).
![2015-10-20_084302](https://cloud.githubusercontent.com/assets/739613/10607349/00262c98-7707-11e5-88af-1ebadb5b71fa.jpg)

**Comment by kitajchuk** [comment]
Is it a content type of `page` or a collection? I was looking at nested collections when I tested this out and everything matched up. I also tested against a static page within an index as well. I'll take a look. This is a good one :P

**Comment by skrichten** [comment]
Its a custom collection, inside a folder.  My folder.conf is in the OP.

**Comment by kitajchuk** [comment]
Weird. I replicated the scenario, a custom collection within a folder. I'm getting a consistent representation of the json data between my local and my remote.

Remote:
<img width="724" alt="screen shot 2015-10-20 at 10 31 18 am" src="https://cloud.githubusercontent.com/assets/438711/10615657/e2637e7c-7715-11e5-8531-773060068de7.png">

Local:
<img width="730" alt="screen shot 2015-10-20 at 10 31 02 am" src="https://cloud.githubusercontent.com/assets/438711/10615651/d9fc4200-7715-11e5-8a9f-673495423ff8.png">

**Comment by kitajchuk** [comment]
Not sure what else is going on here to cause the issue to persist for you... I'll keep an eye on it and keep trying to replicate the issue.

**Comment by skrichten** [comment]
Thanks.  Only differences I can see in the use cases that may or may not make any difference...
I have 3 items at the root level: a folder and 2 custom collections.  In the folder, I have multiple custom collections.  I have 2 navigation's configured in my template.conf... this issue occurs in the second one, haven't checked the first.

**Comment by kitajchuk** [comment]
Been slacking - is this issue still persisting for you @skrichten ?
